import type { ShippingCountryCode } from "./types";

export type Region = { name: string };

export const NG_STATES: ReadonlyArray<Region> = [
  { name: "Abia" },
  { name: "Adamawa" },
  { name: "Akwa Ibom" },
  { name: "Anambra" },
  { name: "Bauchi" },
  { name: "Bayelsa" },
  { name: "Benue" },
  { name: "Borno" },
  { name: "Cross River" },
  { name: "Delta" },
  { name: "Ebonyi" },
  { name: "Edo" },
  { name: "Ekiti" },
  { name: "Enugu" },
  { name: "FCT - Abuja" },
  { name: "Gombe" },
  { name: "Imo" },
  { name: "Jigawa" },
  { name: "Kaduna" },
  { name: "Kano" },
  { name: "Katsina" },
  { name: "Kebbi" },
  { name: "Kogi" },
  { name: "Kwara" },
  { name: "Lagos" },
  { name: "Nasarawa" },
  { name: "Niger" },
  { name: "Ogun" },
  { name: "Ondo" },
  { name: "Osun" },
  { name: "Oyo" },
  { name: "Plateau" },
  { name: "Rivers" },
  { name: "Sokoto" },
  { name: "Taraba" },
  { name: "Yobe" },
  { name: "Zamfara" },
];

export const US_STATES: ReadonlyArray<Region> = [
  { name: "Alabama" },
  { name: "Alaska" },
  { name: "Arizona" },
  { name: "Arkansas" },
  { name: "California" },
  { name: "Colorado" },
  { name: "Connecticut" },
  { name: "Delaware" },
  { name: "District of Columbia" },
  { name: "Florida" },
  { name: "Georgia" },
  { name: "Hawaii" },
  { name: "Idaho" },
  { name: "Illinois" },
  { name: "Indiana" },
  { name: "Iowa" },
  { name: "Kansas" },
  { name: "Kentucky" },
  { name: "Louisiana" },
  { name: "Maine" },
  { name: "Maryland" },
  { name: "Massachusetts" },
  { name: "Michigan" },
  { name: "Minnesota" },
  { name: "Mississippi" },
  { name: "Missouri" },
  { name: "Montana" },
  { name: "Nebraska" },
  { name: "Nevada" },
  { name: "New Hampshire" },
  { name: "New Jersey" },
  { name: "New Mexico" },
  { name: "New York" },
  { name: "North Carolina" },
  { name: "North Dakota" },
  { name: "Ohio" },
  { name: "Oklahoma" },
  { name: "Oregon" },
  { name: "Pennsylvania" },
  { name: "Rhode Island" },
  { name: "South Carolina" },
  { name: "South Dakota" },
  { name: "Tennessee" },
  { name: "Texas" },
  { name: "Utah" },
  { name: "Vermont" },
  { name: "Virginia" },
  { name: "Washington" },
  { name: "West Virginia" },
  { name: "Wisconsin" },
  { name: "Wyoming" },
];

export const CA_PROVINCES: ReadonlyArray<Region> = [
  { name: "Alberta" },
  { name: "British Columbia" },
  { name: "Manitoba" },
  { name: "New Brunswick" },
  { name: "Newfoundland and Labrador" },
  { name: "Northwest Territories" },
  { name: "Nova Scotia" },
  { name: "Nunavut" },
  { name: "Ontario" },
  { name: "Prince Edward Island" },
  { name: "Quebec" },
  { name: "Saskatchewan" },
  { name: "Yukon" },
];

export const REGIONS_BY_COUNTRY: Record<
  ShippingCountryCode,
  ReadonlyArray<Region> | null
> = {
  NG: NG_STATES,
  US: US_STATES,
  CA: CA_PROVINCES,
  GB: null,
};

export const getRegionsForCountry = (
  code: string | null | undefined,
): ReadonlyArray<Region> | null => {
  if (!code) return null;
  return REGIONS_BY_COUNTRY[code as ShippingCountryCode] ?? null;
};
