/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  galleryType?: "image" | "video";
  videoType?: "url" | "file";
  category?: "concept-and-design" | "cover-art";
  conceptType?:
    | "concept-art"
    | "logo"
    | "character-design"
    | "fashion-illustration";
  grade?: "essential" | "advanced";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  videoUrl?: string;
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  videoPreview?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  createdAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Featured = {
  _id: string;
  _type: "featured";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  workUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SanityFileAssetReference
  | Gallery
  | SanityImageCrop
  | SanityImageHotspot
  | Featured
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/queries/query.ts
// Variable: FEATURE_QUERY
// Query: *[_type == "featured"] | order(_createdAt desc){ _id, title, image, workUrl }
export type FEATURE_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  workUrl: string | null;
}>;

// Source: src/sanity/queries/query.ts
// Variable: GALLERY_QUERY
// Query: *[_type == "gallery" && category == $category &&      ($filterParam == null ||       (category == "cover-art" && grade == $filterParam) ||       (category == "concept-and-design" && conceptType == $filterParam))    ] | order(createdAt desc) [$start...$end] {      _id,      galleryType,      videoType,      category,      conceptType,      grade,      image {        asset-> {          _id,          url,          metadata {            lqip,            dimensions          }        }      },      description,      videoUrl,      video {        asset-> {          _id,          url,          mimeType        }      },      videoPreview {        asset-> {          _id,          url,          mimeType        }      },      createdAt    }
export type GALLERY_QUERY_RESULT = Array<{
  _id: string;
  galleryType: "image" | "video" | null;
  videoType: "file" | "url" | null;
  category: "concept-and-design" | "cover-art" | null;
  conceptType:
    | "character-design"
    | "concept-art"
    | "fashion-illustration"
    | "logo"
    | null;
  grade: "advanced" | "essential" | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  description: string | null;
  videoUrl: string | null;
  video: {
    asset: {
      _id: string;
      url: string | null;
      mimeType: string | null;
    } | null;
  } | null;
  videoPreview: {
    asset: {
      _id: string;
      url: string | null;
      mimeType: string | null;
    } | null;
  } | null;
  createdAt: string | null;
}>;

// Source: src/sanity/queries/query.ts
// Variable: GALLERY_COUNT_QUERY
// Query: count(*[_type == "gallery" && category == $category &&      ($filterParam == null ||       (category == "cover-art" && grade == $filterParam) ||       (category == "concept-and-design" && conceptType == $filterParam))    ])
export type GALLERY_COUNT_QUERY_RESULT = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "featured"] | order(_createdAt desc){ _id, title, image, workUrl }': FEATURE_QUERY_RESULT;
    '\n    *[_type == "gallery" && category == $category &&\n      ($filterParam == null ||\n       (category == "cover-art" && grade == $filterParam) ||\n       (category == "concept-and-design" && conceptType == $filterParam))\n    ] | order(createdAt desc) [$start...$end] {\n      _id,\n      galleryType,\n      videoType,\n      category,\n      conceptType,\n      grade,\n      image {\n        asset-> {\n          _id,\n          url,\n          metadata {\n            lqip,\n            dimensions\n          }\n        }\n      },\n      description,\n      videoUrl,\n      video {\n        asset-> {\n          _id,\n          url,\n          mimeType\n        }\n      },\n      videoPreview {\n        asset-> {\n          _id,\n          url,\n          mimeType\n        }\n      },\n      createdAt\n    }\n  ': GALLERY_QUERY_RESULT;
    '\n    count(*[_type == "gallery" && category == $category &&\n      ($filterParam == null ||\n       (category == "cover-art" && grade == $filterParam) ||\n       (category == "concept-and-design" && conceptType == $filterParam))\n    ])\n  ': GALLERY_COUNT_QUERY_RESULT;
  }
}
